services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
#    depends_on:
#      - zookeeper

    ports:
      - "9092:9092"

    environment:
      # Node identity
      KAFKA_NODE_ID: 1

      # KRaft mode
      KAFKA_PROCESS_ROLES: broker,controller

      # Controller quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # Map listener names → protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Which listener controller uses
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Broker listener name
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Single-node convenience
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # REQUIRED in KRaft
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
